### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Barbapapazes** [Barbapapazes/slantire#9]
- [x] Update dependencies
- [x] Move away from document driven mode
- [x] Add `error.vue`
- [x] Add basic SEO
- [x] Add advanced SEO using some SEO module (robots, sitemap, og image)
- [x] Add CI
- [x] Move project under barbapapazes.dev 
- [x] Update readme
